name: Email on Push
on:
  push:
    branches:
      - main   # or whichever branch you want

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "New commit pushed to repo"
          to: your-email@example.com
          from: GitHub Bot <your-email@example.com>
          body: "A new commit was pushed to ${{ github.repository }} by ${{ github.actor }}."
